version: '3'

services:

  vue:
    build: services/vue
    container_name: vue
    restart: always
    working_dir: /www
    command: bash -c "npm run dev"
    volumes:
      - ./web:/www
    ports:
      - 90:8080
